# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-24 09:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0002_customeraddress'),
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='address.Addresses')),
                ('store', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='store.Store')),
            ],
        ),
    ]
