# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-26 04:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_storeaddress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storeaddress',
            name='address',
        ),
        migrations.RemoveField(
            model_name='storeaddress',
            name='store',
        ),
        migrations.DeleteModel(
            name='StoreAddress',
        ),
    ]
