# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-24 09:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0002_customeraddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addresses',
            name='address',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
