# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-28 09:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20170227_0639'),
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartline',
            name='product_id',
        ),
        migrations.AddField(
            model_name='cartline',
            name='store_product',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='store.StoreProducts'),
            preserve_default=False,
        ),
    ]
